### ISSUE TITLE
The package fails to install with github actions

### ISSUE THREAD

**Issue by jsf-3shape** [dword-design/nuxt-mermaid-string#39]
When running `npm ci` as part of a github action`"nuxt-mermaid-string": "^2.0.7"` fails to install.

```bash
npm ci
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/dword-design/endent.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-07-09T08_57_55_959Z-debug.log
Error: Process completed with exit code 1.
```

Running the same script locally works.

**Comment by dword-design** [comment]
@jsf-3shape That's weird. There was a similar [error in another project](https://github.com/dword-design/nuxt-mail/issues/15), maybe it's related. I still can't reproduce it though. I created a [test project in another GitHub account](https://github.com/dword-design-test/try-dword-design-fork/runs/3029180801?check_suite_focus=true) not related to this one and it runs through without problems. Maybe it's related to the CI environment? Node and NPM version? Operating system?

**Comment by jsf-3shape** [comment]
Sorry for the long absence... vacation time.
I suspect it must have been some caching issue with npm.
I switch form using `npm ci` to `npm install` in my ci script and suddenly the issue was gone.
